stages:
  - validate

terraform-validate:
  stage: validate
  image: hashicorp/terraform:latest
  script:
    - |
      set -e
      TEMPLATES_DIR="./templates"
      
      [ ! -d "$TEMPLATES_DIR" ] && { echo "Error: Templates directory not found"; exit 1; }
      
      FAILED=()
      VALIDATED=0
      
      for template_dir in "$TEMPLATES_DIR"/*; do
          if [ -d "$template_dir" ] && [ -f "$template_dir/main.tf" ]; then
              template=$(basename "$template_dir")
              echo "Validating $template..."
              
              TEMP_DIR=$(mktemp -d)
              cp -r "$template_dir"/* "$TEMP_DIR/"
              
              if (cd "$TEMP_DIR" && terraform init -backend=false -get=false >/dev/null 2>&1 && terraform validate >/dev/null 2>&1); then
                  echo "  ✓ $template passed"
                  ((VALIDATED++))
              else
                  echo "  ✗ $template failed"
                  FAILED+=("$template")
              fi
              
              rm -rf "$TEMP_DIR"
          fi
      done
      
      echo -e "\nValidated: $VALIDATED"
      if [ ${#FAILED[@]} -eq 0 ]; then
          echo "✓ All templates passed"
      else
          echo "✗ Failed: ${FAILED[*]}"
          exit 1
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - changes:
        - "templates/**/*.tf"
        - "templates/**/*.tfvars"